### PR TITLE
Increase coverage for hooks

### LINKED ISSUE #320: Increase coverage for hooks
image

https://github.com/user-attachments/assets/2331a71c-6de0-45e7-8898-67216b02e0c3

image

image
image

image

image

image
image

image
image

### PR DESCRIPTION
**Pull request by mhevyk**
- increased unit and mutation test coverage to 100% for all hooks that exist for now
- removed redundant mocks in new and previously created tests

image

image

### CODE REVIEW

**Review by D1nviz — APPROVED** [review]

**Comment by D1nviz** [comment]
Excellent!

**Comment by mhevyk** [comment]
> Excellent!

I appreciate it!

**Review by OliaHrytsak — APPROVED** [review]

**Comment by OliaHrytsak** [comment]
Keep it up!

**Comment by mhevyk** [comment]
> Keep it up!

I'm eternally grateful!

**Review by heshvab — APPROVED** [review]

**Pull request merged**
