### PR TITLE
Add pagination for OrdersPage under ROLE_USER role

### LINKED ISSUE #470: Add pagination for orders tab under ROLE_USER role

### PR DESCRIPTION
**Pull request by mhevyk**
Tested on production:

https://github.com/user-attachments/assets/80942ef0-9ada-4a50-8a8c-ed65481b7f8b

### CODE REVIEW

**Review by D1nviz — APPROVED** [review]

**Comment by D1nviz** [comment]
Nice and quick work!

**Review by OliaHrytsak — APPROVED** [review]

**Comment by OliaHrytsak** [comment]
Reusable components the best!

**Review by heshvab — APPROVED** [review]

**Comment by mhevyk** [comment]
> Nice and quick work!

I am grateful, thanks!

**Comment by mhevyk** [comment]
> Reusable components the best!

For sure!

**Pull request merged**
